// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChoosePrivateKey() {
  return window['go']['main']['App']['ChoosePrivateKey']();
}

export function ClearLog() {
  return window['go']['main']['App']['ClearLog']();
}

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function OpenInteractiveTerminal(arg1) {
  return window['go']['main']['App']['OpenInteractiveTerminal'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}
