// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ChoosePrivateKey():Promise<string>;

export function ClearLog():Promise<void>;

export function GetBootstrap():Promise<model.Bootstrap>;

export function OpenInteractiveTerminal(arg1:model.Profile):Promise<void>;

export function SaveWorkspace(arg1:model.Workspace):Promise<void>;

export function StartTunnel(arg1:model.Profile):Promise<void>;

export function StopTunnel():Promise<void>;
